name: cj_kit
description: cj_kit
version: 0.0.1-dev


environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file: ^6.1.4
  date_format: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
#uses-material-design: true
