name: cj_kit
description: cj_kit
version: 0.1.0-dev


environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file: ^7.0.1
  date_format: ^2.0.7
  logger: ^2.5.0
  intl: ^0.20.1
  path: ^1.9.0
  path_provider: ^2.0.1
  archive: ^3.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:
#uses-material-design: true
